# src/my_email_agent/config/tasks.yaml
retrieve_context_task:
  description: >
    Using the provided Gmail tools, fetch the entire email thread for the given thread ID {thread_id}.
    Retrieve all messages in the thread, including their subjects, senders, recipients, dates, and full bodies.
    Compile this information into a coherent string representation of the full thread context.
  expected_output: >
    A string containing the full email thread context, formatted clearly with each message's details.
  agent: email_retriever
